### ISSUE TITLE
Error is the console

### ISSUE THREAD

**Issue by ILeoI** [DRE2N/FactionsOne#30]
Could you tell me what is wrong?
`20.04 03:43:39 [Server] INFO I__Leo__I issued server command: /f help
20.04 03:43:39 [Server] ERROR null
20.04 03:43:39 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.8.2
20.04 03:43:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
20.04 03:43:39 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
20.04 03:43:39 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
20.04 03:43:39 [Server] INFO Caused by: java.lang.NullPointerException
20.04 03:43:39 [Server] INFO at com.massivecraft.factions.P.onCommand(P.java:193) ~[?:?]
20.04 03:43:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
20.04 03:43:39 [Server] INFO ... 15 more`

Thank you!

**Comment by Sataniel98** [comment]
When does this occur? Which version of F1 are you running? Do you use any addons? Did you load the plugin with a plugin loader like Plugman or something similar?

**Comment by ILeoI** [comment]
I loaded it with PlugMan. The version is v1.2.1-1.8.3. It occurs when I execute any of the plugins commands. No addons
