### ISSUE TITLE
FactionsOne deletes all the data when I stop the server or I reload it

### ISSUE THREAD

**Issue by Sickness2** [DRE2N/FactionsOne#32]
So whenever I want to restart it or stop it and open it again all the data gets removed. Im using spigot 1.8.x

**Comment by Sataniel98** [comment]
About which kind of data are you talking? All of them? I can imagine that you tried to change for example the config while the server was running. Factions doesn't support this because it's a bit unconventional with its (de-) serialization systems.

**Comment by Sickness2** [comment]
No, I didnt change anything of the config while I was testing this, about the data I say, claims, factions, all about that.

**Comment by Sataniel98** [comment]
Does it write something to the files if you do /f save?

**Comment by Sickness2** [comment]
I could try later but what I do, /f create and f claim and later /f save and check the date of the created archives?

**Comment by Sataniel98** [comment]
Creating a faction and claiming something should produce data for both the board and the factions storage. If you do /f save after that, you should be able to see the serialized data if you open board.json and factions.json with a text editor.

**Comment by Sickness2** [comment]
alright, created a faction, did /f save and it throwed this "An internal error ocurred"...:
![fc87438e2c5646aa5d9135ccf1d3a338](https://user-images.githubusercontent.com/29580012/27518802-729b9ce8-59e8-11e7-891b-c004d950781d.png)

**Comment by Sataniel98** [comment]
Are there any other errors in the console? Looks like an issue with Gson.

**Comment by Sickness2** [comment]
I dont know tbh, the console goes so fast but while checking with the eye I cant see any errors.

**Comment by Sickness2** [comment]
java.lang.NoClassDefFoundError: [Lcom/massivecraft/factions/entity/Faction;
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_131]
	at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:1.8.0_131]
	at uk.co.umbaska.registration.Register.getExpressionReturnType(Register.java:419) ~[?:?]
	at uk.co.umbaska.registration.Register.expression(Register.java:177) ~[?:?]
	at uk.co.umbaska.registration.Register.registerElement(Register.java:111) ~[?:?]
	at uk.co.umbaska.registration.Register.registerEverythingFrom(Register.java:86) ~[?:?]
	at uk.co.umbaska.modules.UmbaskaModule.registerSyntaxes(UmbaskaModule.java:69) ~[?:?]
	at uk.co.umbaska.modules.misc.MiscModule.onEnable(MiscModule.java:22) ~[?:?]
	at uk.co.umbaska.modules.UmbaskaModule.enable(UmbaskaModule.java:43) ~[?:?]
	at uk.co.umbaska.modules.ModuleManager.enableModules(ModuleManager.java:79) ~[?:?]
	at uk.co.umbaska.modules.ModuleManager.loadAndEnableModules(ModuleManager.java:50) ~[?:?]
	at uk.co.umbaska.Umbaska.onEnable(Umbaska.java:111) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.entity.Faction
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	... 24 more

It thrown this.

**Comment by Sataniel98** [comment]
I have no idea what Umbaska is, but it is definitely not meant to be used with FactionsOne. There is no com.massivecraft.factions.entity.Faction class. Looks like a Factions 2.x addon. This is not an error thrown by FactionsOne but by Umbaska.

**Comment by Sickness2** [comment]
Is a addon for Skript, well I removed massivecraft folder, there it wasnt any plugin of massivecraft

**Comment by Sataniel98** [comment]
Do you have an old setup that used to include a different Factions plugin?

**Comment by Sickness2** [comment]
Just installed the original Factions, all is working, but it doesnt
generate a folder :(

2017-06-26 14:00 GMT+02:00 Daniel Saukel <notifications@github.com>:

**Comment by Sataniel98** [comment]
I think we're talking a bit past each other now...
- FactionsOne is the original version of Factions maintained by a new guy (aka me), while Factions 2.x (the MassiveCore version) is a relatively new version of Factions maintained by the original team, so what you wrote is a bit ambiguous
- However, FactionsOne has technically few to nothing to do with the MassiveCore version, just like for example Towny and Factions, and both of them are not interchangeable. If you try to change them without deleting _ALL_ of their data, the rests of the data might conflict with the installed plugin even if the deinstalled one isn't even present anymore. Both of them have the same name internally because that allows the old addons to work with FactionsOne.
- Umbaska targets compatibility with the MassiveCore version. It doesn't realize the difference between Factions 2.x and Factions 1.x and therefore, it cannot work with FactionsOne.

So what you can do in order to fix this:
- Get rid of either FactionsOne or MC-Factions and Umbaska, purge all of the data of both plugins
- Start with a clean environment without either FactionsOne or MC-Factions and Umbaska
