### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by Fader-GumGum** [DRE2N/FactionsOne#43]
I'm getting the following error running:
[19:28:29] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-fe3ab0d-ec86574 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[19:28:37] [Server thread/INFO]: [Factions] Loading Factions v1.8.2
on Java 8, update 181
`
[19:28:54] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/massivecraft/factions/RelationParticipator
[19:28:54] [Server thread/WARN]:     at org.mcmonkey.sentinel.SentinelPlugin.onEnable(SentinelPlugin.java:145)
[19:28:54] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:28:54] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[19:28:54] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[19:28:54] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426)
[19:28:54] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340)
[19:28:54] [Server thread/WARN]:     at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562)
[19:28:54] [Server thread/WARN]:     at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524)
[19:28:54] [Server thread/WARN]:     at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423)
[19:28:54] [Server thread/WARN]:     at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288)
[19:28:54] [Server thread/WARN]:     at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686)
[19:28:54] [Server thread/WARN]:     at java.lang.Thread.run(Unknown Source)
[19:28:54] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.RelationParticipator
[19:28:54] [Server thread/WARN]:     at java.net.URLClassLoader.findClass(Unknown Source)
[19:28:54] [Server thread/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154)
[19:28:54] [Server thread/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[19:28:54] [Server thread/WARN]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[19:28:54] [Server thread/WARN]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[19:28:54] [Server thread/WARN]:     ... 12 more
`

**Comment by Sataniel98** [comment]
Definitely on Sentinel's side. It probably supports nothing but Factions 2.x.
