### ISSUE TITLE
Error occurred while enabling Factions v1.8.2

### ISSUE THREAD

**Issue by oflords** [DRE2N/FactionsOne#46]
[01:08:33] [Server thread/INFO]: [Factions] Enabling Factions v1.8.2
[01:08:33] [Server thread/INFO]: [Factions v1.8.2] === ENABLE START ===
[01:08:33] [Server thread/ERROR]: Error occurred while enabling Factions v1.8.2 (Is it up to date?)
java.lang.NoSuchFieldError: STRUCTURE_BLOCK
	at de.erethon.factionsone.LegacyUtil.<clinit>(LegacyUtil.java:74) ~[?:?]
	at com.massivecraft.factions.Conf.<clinit>(Conf.java:255) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.preEnable(MPlugin.java:72) ~[?:?]
	at com.massivecraft.factions.P.onEnable(P.java:82) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[customtaco2.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [customtaco2.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [customtaco2.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [customtaco2.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [customtaco2.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [customtaco2.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [customtaco2.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [customtaco2.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [customtaco2.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [customtaco2.jar:git-TacoSpigot-"95870a93"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

**Comment by oflords** [comment]
Using 1.8.8 TacoSpigot

**Comment by Sataniel98** [comment]
Thanks for the report, I'll fix this as soon as possible!
