### ISSUE TITLE
Doesnt think Plugin is up to date

### ISSUE THREAD

**Issue by OddFoxGames** [DRE2N/FactionsOne#7]
[10:46:18 INFO]: Nerfing mobs spawned from spawners: false
[10:46:18 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:46:18 INFO]: Random Lighting Updates: false
[10:46:18 INFO]: Structure Info Saving: true
[10:46:18 INFO]: Sending up to 10 chunks per packet
[10:46:18 INFO]: Max TNT Explosions: 100
[10:46:18 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:46:18 INFO]: Item Merge Radius: 2.5
[10:46:18 INFO]: Item Despawn Rate: 6000
[10:46:18 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:46:18 INFO]: View Distance: 10
[10:46:18 INFO]: Zombie Aggressive Towards Villager: true
[10:46:18 INFO]: Chunks to Grow per Tick: 650
[10:46:18 INFO]: Clear tick list: false
[10:46:18 INFO]: Experience Merge Radius: 3.0
[10:46:18 INFO]: Max Entity Collisions: 8
[10:46:18 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[10:46:18 INFO]: -------- World Settings For [world_the_end] --------
[10:46:18 INFO]: Arrow Despawn Rate: 1200
[10:46:18 INFO]: Mob Spawn Range: 4
[10:46:18 INFO]: Anti X-Ray: false
[10:46:18 INFO]:        Engine Mode: 1
[10:46:18 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74,
82, 129, 130]
[10:46:18 INFO]:        Replace Blocks: [1, 5]
[10:46:18 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[10:46:18 INFO]: Cactus Growth Modifier: 100%
[10:46:18 INFO]: Cane Growth Modifier: 100%
[10:46:18 INFO]: Melon Growth Modifier: 100%
[10:46:18 INFO]: Mushroom Growth Modifier: 100%
[10:46:18 INFO]: Pumpkin Growth Modifier: 100%
[10:46:18 INFO]: Sapling Growth Modifier: 100%
[10:46:18 INFO]: Wheat Growth Modifier: 100%
[10:46:18 INFO]: NetherWart Growth Modifier: 100%
[10:46:18 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:46:18 INFO]: Nerfing mobs spawned from spawners: false
[10:46:18 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:46:18 INFO]: Random Lighting Updates: false
[10:46:18 INFO]: Structure Info Saving: true
[10:46:18 INFO]: Sending up to 10 chunks per packet
[10:46:18 INFO]: Max TNT Explosions: 100
[10:46:18 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:46:18 INFO]: Item Merge Radius: 2.5
[10:46:18 INFO]: Item Despawn Rate: 6000
[10:46:18 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:46:18 INFO]: View Distance: 10
[10:46:18 INFO]: Zombie Aggressive Towards Villager: true
[10:46:18 INFO]: Chunks to Grow per Tick: 650
[10:46:18 INFO]: Clear tick list: false
[10:46:18 INFO]: Experience Merge Radius: 3.0
[10:46:18 INFO]: Max Entity Collisions: 8
[10:46:18 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[10:46:18 INFO]: Preparing start region for level 0 (Seed: 5178481685094233390)
[10:46:19 INFO]: Preparing start region for level 1 (Seed: 5178481685094233390)
[10:46:20 INFO]: Preparing start region for level 2 (Seed: 5178481685094233390)
[10:46:20 INFO]: [BowHealth] Enabling BowHealth v1.0
[10:46:20 INFO]: BowHealth is now disabled!
[10:46:20 INFO]: [MobStacker] Enabling MobStacker v1.8.3
[10:46:20 INFO]: [MobStacker] MobStacker is starting
[10:46:20 INFO]: [MobStacker] Connected to metrics
[10:46:20 INFO]: [MobStacker] Didn't hook in to WorldGuard
[10:46:20 INFO]: [MobStacker] MobStacker has successfully started!
[10:46:20 INFO]: [InventorySort] Enabling InventorySort v1.1.1
[10:46:20 INFO]: [Enderpearl_Cooldown] Enabling Enderpearl_Cooldown v1.0 Stable
[10:46:20 INFO]: [EditableSign] Enabling EditableSign v2.4.0
[10:46:20 INFO]: [EditableSign] EditableSign version 2.4.0 is Enabled
[10:46:20 INFO]: [TOSP] Enabling ThatOneSpawnPlugin v1.0.4
[10:46:20 INFO]: [ClearLag] Enabling ClearLag v2.9.1
[10:46:20 INFO]: [ClearLag] Loading modules...
[10:46:20 INFO]: [ClearLag] Modules enabed, loading config values
[10:46:20 INFO]: [ClearLag] Modules have been loaded!
[10:46:20 INFO]: [ClearLag] Clearlag is now enabled!
[10:46:20 INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
[10:46:20 INFO]: [ClearLag] Checking for updates...
[10:46:20 INFO]: [PermissionsEx] Initializing file backend
[10:46:20 INFO]: [PermissionsEx] Permissions file successfully reloaded
[10:46:20 INFO]: [Vault][Permission] PermissionsEx hooked.
[10:46:20 INFO]: [Vault][Chat] PermissionsEx_Chat hooked.
[10:46:20 INFO]: [GoldenAppleControl] Enabling GoldenAppleControl v2.0.2
[10:46:20 ERROR]: [GoldenAppleControl] Your config is outdated!
[10:46:20 ERROR]: [GoldenAppleControl] The plugin will not load unless you chang
e the config version to 8.
[10:46:20 ERROR]: [GoldenAppleControl] This means that you will need to reset yo
ur config, as there may have been major changes to the plugin.
[10:46:20 INFO]: [GoldenAppleControl] Disabling GoldenAppleControl v2.0.2
[10:46:20 INFO]: [SpawnJoin] Enabling SpawnJoin v4.1.4
[10:46:20 INFO]: [SpawnJoin] Registering SpawnJoin event listeners...
[10:46:20 INFO]: [SpawnJoin] Event listeners registered! Resistering enabled com
mands...
[10:46:20 INFO]: [SpawnJoin] All enabled commands now registered!
[10:46:21 INFO]: [ClearLag] No updates found!
[10:46:21 INFO]: [SpawnJoin] A new version of SpawnJoin is available: 5.0.0
[10:46:21 INFO]: [SpawnJoin] Download it at: http://dev.bukkit.org/bukkit-plugin
s/teleport-spawn-join/files/19-spawn-join-version-5-0-0/
[10:46:21 INFO]: [WorldBorder] Enabling WorldBorder v1.8.5
[10:46:21 INFO]: [WorldBorder] [CONFIG] Using elliptic/round border, knockback o
f 3.0 blocks, and timer delay of 5.
[10:46:21 INFO]: [WorldBorder] [CONFIG] Border-checking timed task started.
[10:46:21 INFO]: [WorldBorder] For reference, the main world's spawn location is
 at X: 188.0 Y: 64.0 Z: 256.0
[10:46:21 INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.1.10
[10:46:21 INFO]: [CustomEnchantments] Enabling CustomEnchantments v2.4c
[10:46:21 INFO]: [CE] ERROR: The ChatColor 'O' was not found, please check the l
ist of Bukkit ChatColors and update the ChatColor Section. The ChatColor will be
 ignored to ensure that CE is still working.
[10:46:21 INFO]: [CE] Vault has been detected!
[10:46:21 INFO]: [CE] All Enchantments have been loaded.
[10:46:21 INFO]: [CE] All Items have been loaded.
[10:46:22 INFO]: [FactionPotions] Enabling FactionPotions v1.0.0
[10:46:22 INFO]: [FactionPotions] FactionPotions version 1.0.0 is Enabled
[10:46:22 INFO]: [SurvivalStats] Enabling SurvivalStats v1.2
[10:46:22 INFO]: >> SurvivalStats is enabled!
[10:46:22 INFO]: [Essentials] Enabling Essentials v2.0.1-b267
[10:46:22 INFO]: Using locale en_US
[10:46:22 INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as spawner pr
ovider.
[10:46:22 INFO]: Using locale en_US
[10:46:22 INFO]: [Essentials] Starting Metrics. Opt-out using the global PluginM
etrics config.
[10:46:22 INFO]: [Vault][Economy] Essentials Economy hooked.
[10:46:22 INFO]: [PlayerVaults] Enabling PlayerVaults v3.5.6-b181
[10:46:22 INFO]: [ChatManagerReloaded] Enabling ChatManagerReloaded v2.0
[10:46:22 INFO]: ChatManager> Hooked Permission_PermissionsEx
[10:46:22 INFO]: ChatManager> Hooked Chat_PermissionsEx
[10:46:22 INFO]: ChatManager> Hooked Economy_Essentials
[10:46:22 INFO]: ChatManager> The Plugin has been loaded successfully
[10:46:22 INFO]: ChatManager> Another Chatsystem has been detected! Make sure di
sabling it, to use all functions from ChatManagerReloaded. (Ignore, if its part
of an permission-system)
[10:46:22 INFO]: [Factions] Enabling Factions v1.8.2
[10:46:22 INFO]: [FactionsOne v1.2.2] === ENABLE START ===
[10:46:22 ERROR]: Error occurred while enabling Factions v1.8.2 (Is it up to dat
e?)
java.lang.NoSuchFieldError: SHULKER
        at com.massivecraft.factions.Conf.<clinit>(Conf.java:364) ~[?:?]
        at com.massivecraft.factions.zcore.MPlugin.preEnable(MPlugin.java:80) ~[
?:?]
        at com.massivecraft.factions.P.onEnable(P.java:96) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[s
pigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.jav
a:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.
java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:4
14) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:3
78) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:3
33) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.jav
a:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
[10:46:22 INFO]: [CombatTagPlus] Enabling CombatTagPlus v1.2.1
[10:46:22 INFO]: [SilkSpawners] Enabling SilkSpawners v3.7.3
[10:46:23 INFO]: [SilkSpawners] WorldGuard was not found and support is disabled

[10:46:23 INFO]: [SilkSpawners] Loading support for v1_8_R3
[10:46:23 INFO]: [SilkSpawners] AutoUpdater is enabled.
[10:46:23 INFO]: [SilkSpawners] Result from AutoUpdater is: NO_UPDATE
[10:46:23 INFO]: [SilkSpawners] BarAPI is disabled due to config setting.
[10:46:23 INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:46:23 INFO]: Done (4.787s)! For help, type "help" or "?"
[10:46:23 INFO]: [Enderpearl_Cooldown] Unable to connect to MiBlue Plugin listin
g. Will run anyway: http://miblue.net/plugins.txt
[10:46:23 WARN]: java.io.FileNotFoundException: http://miblue.net/plugins.txt
[10:46:23 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputS
tream0(Unknown Source)
[10:46:23 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputS
tream(Unknown Source)
[10:46:23 WARN]:        at java.net.URL.openStream(Unknown Source)
[10:46:23 WARN]:        at net.miblue.enderpearlcooldown.EnderpearlCooldown.chec
kMiBlueListing(EnderpearlCooldown.java:56)
[10:46:23 WARN]:        at net.miblue.enderpearlcooldown.EnderpearlCooldown.acce
ss$0(EnderpearlCooldown.java:53)
[10:46:23 WARN]:        at net.miblue.enderpearlcooldown.EnderpearlCooldown$1.ru
n(EnderpearlCooldown.java:35)
[10:46:23 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.ru
n(CraftTask.java:71)
[10:46:23 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftSchedul
er.mainThreadHeartbeat(CraftScheduler.java:350)
[10:46:23 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(Minecr
aftServer.java:723)
[10:46:23 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(Dedica
tedServer.java:374)
[10:46:23 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(Minecr
aftServer.java:654)
[10:46:23 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(Mine
craftServer.java:557)
[10:46:23 WARN]:        at java.lang.Thread.run(Unknown Source)
[10:46:23 INFO]: [PlayerVaults] We didn't find an update!
[10:46:23 INFO]: [PlayerVaults] ** Vaults have already been converted to UUIDs.
If this is incorrect, shutdown your server and rename the plugins\PlayerVaults\u
uidvaults directory.
[10:46:23 INFO]: [HolographicDisplays] Found a new version available: v2.2
[10:46:23 INFO]: [HolographicDisplays] Download it on Bukkit Dev:
[10:46:23 INFO]: [HolographicDisplays] dev.bukkit.org/bukkit-plugins/holographic
-displays
[10:46:23 INFO]: [Vault] Checking for Updates ...
[10:46:23 INFO]: com.mojang.authlib.GameProfile@517bf798[id=f2c7f95d-4a18-4fbe-b
bc8-f5923b0085d2,name=DeKire,properties={textures=[com.mojang.authlib.properties
.Property@162c24b1]},legacy=false] (/127.0.0.1:49688) lost connection: Disconnec
ted
[10:46:23 INFO]: [Vault] No new version available
[10:46:24 INFO]: DeKire[/127.0.0.1:49695] logged in with entity id 115 at ([worl
d]281.92775174365516, 77.85427170309416, 298.71115736862845)
[10:46:24 INFO]: Plugins (22): BowHealth, MobStacker, InventorySort, Enderpearl_
Cooldown, EditableSign, ThatOneSpawnPlugin, ClearLag, PermissionsEx, GoldenApple
Control, SpawnJoin, WorldBorder, HolographicDisplays, Vault, CustomEnchantments,
 FactionPotions, SurvivalStats, Essentials, PlayerVaults, ChatManagerReloaded, F
actions, CombatTagPlus, SilkSpawners
[10:46:31 INFO]: DeKire issued server command: /pl
[10:46:35 INFO]: DeKire issued server command: /f create
[10:46:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' i
n plugin Factions v1.8.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServe
r.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerCon
nection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java
:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java
:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar
:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
15) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
        at com.massivecraft.factions.P.onCommand(P.java:193) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got.jar:git-Spigot-db6de12-18fbb24]
        ... 15 more
[10:46:37 INFO]: DeKire issued server command: /f create
[10:46:37 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' i
n plugin Factions v1.8.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServe
r.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerCon
nection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java
:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java
:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar
:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
15) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
        at com.massivecraft.factions.P.onCommand(P.java:193) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got.jar:git-Spigot-db6de12-18fbb24]
        ... 15 more
[10:46:38 INFO]: [CE] Checking for updates...
[10:46:38 INFO]: [CE] You are using the latest Version of CE!
>

**Comment by Sataniel98** [comment]
Your server is the thing that is not up to date ^^ Either use v1.2.1 instead or update to 1.9 or higher.
