### ISSUE TITLE
java.lang.NoSuchFieldError: SHULKER

### ISSUE THREAD

**Issue by doozzik** [DRE2N/FactionsOne#9]
Spigot 1.8.8
FactionsOne 1.2.2
Error on starting server.

```
[18:19:36] [Server thread/INFO]: [Factions] Enabling Factions v1.8.2
[18:19:36] [Server thread/INFO]: [FactionsOne v1.2.2] === ENABLE START ===
[18:19:36] [Server thread/ERROR]: Error occurred while enabling Factions v1.8.2 (Is it up to date?)
java.lang.NoSuchFieldError: SHULKER
	at com.massivecraft.factions.Conf.<clinit>(Conf.java:364) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.preEnable(MPlugin.java:80) ~[?:?]
	at com.massivecraft.factions.P.onEnable(P.java:96) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
```

**Comment by doozzik** [comment]
Sorry, wrong version.
